/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
var DomainSwitcher=function(){function g(a){if(a=document.getElementById(a))a.style.display="block"}function f(a){if(a=document.getElementById(a))a.style.display="none"}function k(a){var c=document.getElementById("mydomain_preview"),d=document.getElementById("mydomain_suffix").value,e=document.getElementById("community_suffix").value,b=a.value.replace(/^\s+|\s+$/g,""),h=!1;b||(h=!0,b="\x3cem\x3edomain\x3c/em\x3e");for(b.match(/^[-./A-Za-z0-9]+$/)&&a.removeAttribute("style");c.firstChild;)c.removeChild(c.firstChild);
a=b.indexOf(".");d=-1===a?"https://"+b+d:0!==a&&0===d.indexOf(b.substring(a))?"https://"+b.substring(0,a)+d:0!==a&&0===e.indexOf(b.substring(a))?"https://"+b.substring(0,a)+e:"https://"+b;h?c.innerHTML=d:(h=document.createTextNode(d),c.appendChild(h))}return{handleMyDomain:function(){var a=document.getElementById("mydomain"),c=a.value.replace(/^\s+|\s+$/g,"");if(c.match(/^[-./A-Za-z0-9]+$/)){var a=window.SFDCSessionVars&&window.SFDCSessionVars.usec?"http://":"https://",d=document.getElementById("mydomain_suffix"),
e=document.getElementById("community_suffix"),b=c.indexOf("."),a=-1===b?a+(c+d.value):0!==b&&0===d.value.indexOf(c.substring(b))?a+(c.substring(0,b)+d.value):0!==b&&0===e.value.indexOf(c.substring(b))?a+(c.substring(0,b)+e.value):a+c;(c=document.getElementById("pqs"))?c.value&&"?"===c.value.substring(0,1)&&(a+=c.value):(c=document.getElementById("login_startUrl"))&&(c.value&&""!==c.value)&&(a=encodeURIComponent?a+("?startURL\x3d"+encodeURIComponent(c.value)):a+("?startURL\x3d"+c.value));window.location=
a}else a.style.border="#f00 1px solid"},updateMyDomain:function(a,c){k(a);var d=document.getElementById("mydomain_suffix").value,e=document.getElementById("community_suffix").value,b=d.indexOf(":"),d=-1===b?d:d.substring(0,b),b=e.indexOf(":"),e=-1===b?e:e.substring(0,b),d=[d,e],e=a.value;if(a&&(0!==a.value.length&&c)&&(b=a.setSelectionRange?c.which:c.keyCode,!(32>b||33<=b&&46>=b||112<=b&&123>=b))){var h;a.setSelectionRange?h=a.selectionStart:(b=document.selection.createRange(),b.parentElement()===
a&&(h=a.value.lastIndexOf(b.text)));for(var b=e.indexOf("."),f=0;f<d.length;f++){var g=d[f];if(0<b&&0===g.toLowerCase().indexOf(e.toLowerCase().substring(b))){a.value+=g.substring(e.length-b,g.length);break}}a.setSelectionRange?a.setSelectionRange(h,a.value.length):(b=a.createTextRange(),b.moveStart("character",h),b.moveEnd("character",a.value.length),b.select())}},enterCustomDomain:function(a,c){g("mydomainContainer");g("header");document.title=a+c;var d=document.getElementById("header");d&&(d.innerHTML=
a);f("theloginform");f("signup");d=document.getElementById("mydomain");k(d);0<d.offsetWidth&&(f("mydomain_preview"),document.getElementById("mydomain_preview").style.maxWidth=d.offsetWidth+"px",g("mydomain_preview"));d.focus()},dismissCustomDomain:function(a,c){f("mydomainContainer");f("header");g("theloginform");g("signup");f("error");document.title=a+c;document.getElementById("assistive-announce").innerHTML=a}}}();
var IdpOptions=function(){function e(a){if(a=document.getElementById(a))a.style.display="block"}function d(a){if(a=document.getElementById(a))a.style.display="none"}function p(a){var b=document.getElementById("header");b&&(b.innerHTML=a)}function q(){if(!(0<k.length)){var a=document.getElementById("idplist");if(a)for(var a=a.childNodes,b=0;b<a.length;b++)k.push({name:a[b].getElementsByTagName("span")[0].innerHTML,elem:a[b]})}}function r(a,b,f){for(var c=a.elem.firstChild;c.lastChild&&"span"===c.lastChild.nodeName.toLowerCase();)c.removeChild(c.lastChild);
if(null!==b&&null!==f){var g="",d=null,e=null,h=null;f=f.length;0===b?(d=a.name.substring(0,f),e=a.name.substring(f),g="a"):(g="b",d=a.name.substring(0,b),b+f>=a.name.length?e=a.name.substring(b):(e=a.name.substring(b,b+f),h=a.name.substring(b+f)));b=document.createElement("span");b.appendChild(document.createTextNode(d));"a"===g&&(b.style.fontWeight="bolder");c.appendChild(b);null!==e&&(d=document.createElement("span"),d.appendChild(document.createTextNode(e)),"b"===g&&(d.style.fontWeight="bolder"),
c.appendChild(d));null!==h&&(g=document.createElement("span"),g.appendChild(document.createTextNode(h)),c.appendChild(g))}else h=document.createElement("span"),h.appendChild(document.createTextNode(a.name)),c.appendChild(h);return a.elem}function m(a){s();var b=document.getElementById("idplist").childNodes;"down"===a&&h<b.length-1?h++:"up"===a&&-1<h&&h--;if(-1<h&&h<b.length&&(a=b[h].firstChild,document.getElementById("idp_search").setAttribute("aria-activedescendant",a.id),a.setAttribute("style",
"background-color: #eef1f6;"),1<b.length&&(document.getElementById("idp_search").value=a.getAttribute("title")),4<b.length)){a=document.getElementById("idpscrollable");var f=a.scrollTop,c=b[h].offsetHeight*h;c<f?a.scrollTop=c:c>f+a.clientHeight&&(a.scrollTop=c-3*b[h].offsetHeight)}}function s(){for(var a=document.getElementById("idplist").childNodes,b=0;b<a.length;b++)a[b].firstChild.setAttribute("style","background-color:white;")}function n(){return"idphint_"+window.location.pathname}function t(a){if("button"===
a.nodeName.toLowerCase())return a.cloneNode(!0);var b=a.firstChild;a=document.createElement("button");a.setAttribute("class","button mb8 secondary wide");a.setAttribute("onclick",b.getAttribute("onclick"));var f=b.firstChild,b=b.lastChild;-1===f.src.indexOf("/img/s.gif")&&a.appendChild(f.cloneNode(!0));a.appendChild(b.cloneNode(!0));return a}var k=[],h=-1,l=window.localStorage?window.localStorage:null;return{enterIdp:function(a,b){e("idp_section_chooser");e("cancel_idp_div");e("header");document.title=
a+b;p(a);d("content");d("choose_idp");d("employee_login");document.getElementById("idp_search").focus()},dismissIdp:function(a,b){d("idp_section_chooser");d("cancel_idp_div");d("header");d("error");e("content");e("choose_idp");e("employee_login");document.title=a+b},searchIdps:function(a){q();if(38===a.keyCode)m("up");else if(40===a.keyCode)m("down");else if(13===a.keyCode)a=document.getElementById("idplist").childNodes,-1<h&&h<a.length&&a[h].firstChild.click();else{h=-1;s();document.getElementById("idp_search").setAttribute("aria-activedescendant",
"");document.getElementById("idpscrollable").scrollTop=0;a=document.getElementById("idp_search").value;for(var b=[],f=[],c=document.getElementById("idplist");c.firstChild;)c.removeChild(c.firstChild);var c=document.getElementById("idplist"),g;for(g=0;g<k.length;g++){var d=k[g],e=RegExp(a.toLowerCase().replace(/[\-\/\\\^$*+?.()|\[\]{}]/g,"\\$\x26"));d.name.toLowerCase().match(e)&&(e=d.name.toLowerCase().search(e),0===e?b.push(r(d,e,a)):f.push(r(d,e,a)))}for(g=0;g<b.length;g++)c.appendChild(b[g]);for(g=
0;g<f.length;g++)c.appendChild(f[g]);1===c.childNodes.length&&m("down")}},useIdp:function(a,b){if(null!==l)try{l.setItem(n(),a)}catch(d){}window.location.href=b},checkIdpHint:function(a,b){if(null===l)return!1;var f=l.getItem(n());if(f){q();if(!(0<k.length)){var c=document.getElementById("idp_section_buttons");if(c)for(var c=c.childNodes,g=0;g<c.length;g++)k.push({name:c[g].getElementsByTagName("span")[0].innerHTML,elem:c[g]})}for(c=0;c<k.length;c++)if(k[c].name===f)return document.getElementById("idp_hint").appendChild(t(k[c].elem)),
e("idp_hint_section"),e("header"),document.title=a+b,p(a),d("content"),d("choose_idp"),d("or_use_idp"),d("idp_section_buttons"),d("idp_section_chooser"),!0}else if((f=document.getElementById("idp_section_chooser"))&&"none"!==f.style.display)(f=document.getElementById("idp_search"))&&f.focus();return!1},clearIdpHint:function(a){null!==l&&l.removeItem(n());d("idp_hint_section");a&&(document.getElementById("login_form")?(d("header"),d("error"),e("content"),e("choose_idp"),e("or_use_idp"),e("idp_section_buttons")):
(e("idp_section_buttons"),e("idp_section_chooser"),(a=document.getElementById("idp_search"))&&a.focus()))}}}();
var LoginHint=function(b){function p(a,k){(!b.lh||!document.getElementById("username"))&&IdpOptions.checkIdpHint(b.hidp,b.title)?g&&(window.clearTimeout(g),g=null):SfdcApp.SfdcSession.getIdentities({get:[],callback:function(c){g&&(window.clearTimeout(g),g=null);c=c.identities;if(a){var d=[],e=b.im,l=b.ic,f;for(f in c)if(c.hasOwnProperty(f)){var h=c[f];if(l||!h.community)e&&!h.mydomain||l&&!h.community||(e||l)&&b.ur!=c[f].identity.instance||(d[f]=h)}f=n(d);LoginHint.Ui.renderEdit(f,b.ah,b.ih,b.save)}else q(c);
k()}})}function n(a){var b=[],c=[],d;for(d in a)if(a.hasOwnProperty(d)){var e=a[d];e.active?b.push(e):c.push(e)}a=b.sort(function(a,c){return c.lastused-a.lastused});c=c.sort(function(a,c){return c.lastused-a.lastused});return a.concat(c)}function q(a){var k=0,c=[],d=b.im,e=b.ic,l;for(l in a)if(a.hasOwnProperty(l)){var f=a[l];if(e||!f.community)if(!(d&&!f.mydomain||e&&!f.community))if(!((d||e)&&b.ur!=a[l].identity.instance)&&r(a[l].identity.instance))k++,c[l]=f}a=1<k?n(c):c;LoginHint.Ui.renderIdentities(b.suo,
b.sum,b.hac,b.heu,b.lpt,b.ah,b.ih,k,a,b.lh,b.le,b.lp,b.title,d,e);SFDCSessionVars.hintRendered=!0}function r(a){return a&&6<a.length?(a=a.substring(0,6),"http:/"===a||"https:"===a):!1}function u(){var a=document.getElementById("content");a&&(a.style.display="block",loader());if(a=document.getElementById("signup"))a.style.display="block";g=null}function s(a,b){LoginHint.Ui.useIdentity(a,b,!1)}function t(a){p(a,function(){})}var g=null,m=[];return{showChooser:function(){LoginHint.Ui.showChooser()},
useNewIdentity:function(){LoginHint.Ui.useNewIdentity()},clearExistingIdentity:function(){LoginHint.Ui.clearExistingIdentity()},showEdit:function(){m=[];t(!0);LoginHint.Ui.showEdit()},hideLoginForm:function(){if(window.setTimeout&&!SfdcApp.SfdcSession.disabled){var a=!1;try{var b=document.styleSheets,c;for(c in b)if(b.hasOwnProperty&&b.hasOwnProperty(c)){var d=b[c];if(d.cssRules){d.insertRule?(d.insertRule("#content { display:none; }",d.cssRules.length),d.insertRule("#signup { display:none; }",d.cssRules.length),
a=!0):d.addRule&&(d.addRule("#content","display:none;"),d.addRule("#signup","display:none;"),a=!0);break}}}catch(e){}a&&(g=window.setTimeout(u,1500))}},useIdentity:s,getSavedIdentities:t,sortResults:n,deleteIdentity:function(a,k){m.push({oid:a,uid:k});var c=document.getElementById("edit-"+(a+k));c.parentNode.removeChild(c);document.getElementById("hint_save_edit").innerHTML=1===m.length?b.saveOne:b.saveMany.replace("#p#",m.length);document.getElementById("assistive-announce").innerHTML=b.dc},saveHintEdit:function(){if(0<
m.length){for(var a,k=0;k<m.length;k++){var c=m[k],d=document.getElementById("hint_"+(c.oid+c.uid));a=d.parentNode;a.removeChild(d);SfdcApp.SfdcSession.deleteIdentity({oid:c.oid,uid:c.uid})}0===a.childNodes.length?LoginHint.Ui.noSavedIdentity():LoginHint.showChooser();LoginHint.Ui.updateSavedText(b.suo,b.sum,a.childNodes.length)}else LoginHint.showChooser()},renderIdentities:q,executeActive:function(a,b,c,d,e,l,f,h){if(r(d))if(new Date(c)<new Date){var g=null;h=function(){g&&(window.clearTimeout(g),
g=null);p(!1,function(){if(f){var a=d,b=document.getElementById("pqs"),a=b&&b.value?a+(b.value+"\x26"):a+"?";window.location=a+"stbdtimeout\x3d1\x26login_hint\x3d"+encodeURIComponent(e)}else s(e,l)})};window.setTimeout&&(g=window.setTimeout(h,1E3));SfdcApp.SfdcSession.inactive({oid:a,uid:b,callback:h})}else c="",h&&(c+="\x26icom\x3d1"),(h=document.getElementById("pqs"))&&(h.value&&"?"===h.value.substring(0,1))&&(c+="\x26q\x3d"+encodeURIComponent(h.value)),window.location=d+"/secur/loginhint?o\x3d"+
a+c+"\x26u\x3d"+b+"\x26un\x3d"+encodeURIComponent(e)+"\x26retURL\x3d"+encodeURIComponent(document.getElementById("login_startUrl").value)}}}(SFDCSessionVars);
if(!this.LoginHint)var LoginHint={};
LoginHint.Ui=function(){function f(a){if(a=document.getElementById(a))a.style.display="block"}function e(a){if(a=document.getElementById(a))a.style.display="none"}function G(a){var c=document.getElementById("header");c&&(c.innerHTML=a)}function H(a){var c=document.getElementById("assistive-announce");c&&(c.innerHTML=a)}function l(){f("content");n?(f("chooser"),f("use_new_identity_div"),f("header"),G(w),document.title=w+x,H(w)):(e("chooser"),e("use_new_identity_div"));u?(f("manager"),f("header"),G(y),
document.title=y+x):e("manager");p?(f("error"),f("chooser_error")):(e("error"),e("chooser_error"));null!==h&&(document.getElementById("username").value=h);r?(f("theloginform"),f("signup"),f("employee_login"),f("or_use_idp"),f("idp_section_buttons"),f("choose_idp"),e("header"),document.title=z+x,H(z),v?(f("username"),e("idcard-container")):(e("username"),f("idcard-container"))):(e("theloginform"),e("signup"),e("employee_login"),e("or_use_idp"),e("idp_section_buttons"),e("choose_idp"));var a=document.getElementById(s);
r&&(a&&a.focus)&&a.focus()}function A(a){n=!0;u=r=!1;p=a?!0:!1;l()}function E(a,c){n=!1;p=v=r=!0;u=!1;h=a?a:B?"":null;s=c?"password":"username";l()}function F(a,c,b){n=!1;r=!0;p=v=!1;h=a;s="password";if((a=document.getElementById("rememberUn"))&&!b)a.checked=!0;document.getElementById("idcard").setAttribute("aria-label",h);b=document.getElementById("idcard-avatar");b.src=c;b.title=h;c=document.getElementById("idcard-identity");c.innerHTML="";c.appendChild(document.createTextNode(h));l()}function I(){u=
n=!1;p=v=r=!0;h=null;s="username";l()}function C(a,c,b){if(a.addEventListener)a.addEventListener(c,b,!1);else if(a.attachEvent)a.attachEvent("on"+c,b);else throw"Could not add handler "+c;}function N(a){a=a||window.event;a=m[(a.target||a.srcElement).paramkey];LoginHint.deleteIdentity(a.oid,a.uid)}function O(a,c,b){var d;d=a.identity.display?a.identity.display:a.identity.username;var g=a.identity.oid+a.identity.uid,k=document.createElement("li");k.setAttribute("id","edit-"+g);var f=J(a,d);c=K(a,c,
b);d=L(a,d);g="editp"+g+(new Date).getTime();m[g]={oid:a.identity.oid,uid:a.identity.uid,username:a.identity.username};a=document.createElement("a");a.setAttribute("href","#");a.setAttribute("onclick","return false;");a.setAttribute("class","hintclearlink");a.paramkey=g;C(a,"click",N);b=document.createElement("img");b.setAttribute("alt","");b.setAttribute("class","hintclearicon");b.setAttribute("src","/img/clear.png");b.paramkey=g;a.appendChild(b);k.appendChild(f);k.appendChild(c);k.appendChild(a);
k.appendChild(d);return k}function P(a){a=a||window.event;a=m[(a.target||a.srcElement).paramkey];LoginHint.executeActive(a.oid,a.uid,a.expire,a.instance,a.username,a.thumbnail,a.otherDom,a.community)}function Q(a){a=a||window.event;window.location=m[(a.target||a.srcElement).paramkey].redir}function R(a){a=a||window.event;a=m[(a.target||a.srcElement).paramkey];LoginHint.useIdentity(a.username,a.thumbnail)}function M(a,c,b,d){var g=!c&&(a.mydomain||a.community),k=a.identity.oid+a.identity.uid,f;f=a.identity.display?
a.identity.display:a.identity.username;c=document.createElement("li");c.setAttribute("id","hint_"+k);var e=document.createElement("a");e.setAttribute("href","#");e.setAttribute("onclick","return false;");k="hintclick"+k+(new Date).getTime();if(a.active)m[k]={oid:a.identity.oid,uid:a.identity.uid,expire:a.expire,instance:a.identity.instance,username:a.identity.username,thumbnail:a.identity.thumbnail,otherDom:g,community:a.community},C(e,"click",P);else if(g){var g=a.identity.instance,h=document.getElementById("pqs"),
g=h&&h.value?g+(h.value+"\x26"):g+"?",g=g+("stbdtimeout\x3d1\x26login_hint\x3d"+encodeURIComponent(a.identity.username));m[k]={redir:g};C(e,"click",Q)}else m[k]={username:a.identity.username,thumbnail:a.identity.thumbnail},C(e,"click",R);e.paramkey=k;c.paramkey=k;g=J(a,f);g.paramkey=k;e.appendChild(g);b=K(a,b,d);e.appendChild(b);a=L(a,f);a.paramkey=k;e.appendChild(a);c.appendChild(e);return c}function J(a,c){var b=document.createElement("img");b.setAttribute("class","thumbnail");b.setAttribute("alt",
"");b.setAttribute("title",c);b.setAttribute("src",a.identity.thumbnail);return b}function K(a,c,b){var d=document.createElement("img");d.setAttribute("class","activity");d.setAttribute("src",a.active?"/img/greendot.png":"/img/greydot.png");d.setAttribute("alt",a.active?c:b);return d}function L(a,c){var b=document.createElement("span");b.appendChild(document.createTextNode(c));return b}function D(a,c,b){var d=document.getElementById("hint_back_chooser");d||(d=document.createElement("a"),d.setAttribute("id",
"hint_back_chooser"),d.setAttribute("href","#"),d.setAttribute("onclick","LoginHint.showChooser(); return false;"),d.setAttribute("class","fr small"),document.getElementById("usernamegroup").insertBefore(d,document.getElementById("username_container")));1==b?d.innerHTML=a:1<b?d.innerHTML=c.replace("#p#",b):d.parentNode.removeChild(d);if(d=document.getElementById("chooser_label"))d.innerHTML=1==b?a:c.replace("#p#",b)}var B=!1,n=!1,r=!1,v=!0,p=!1,u=!1,h="",s="password",m={},w="",y="",z="",x="";return{showChooser:A,
useNewIdentity:function(){n=!1;v=r=!0;p=!1;h="";s="username";l()},showEdit:function(){n=!1;u=!0;l()},updateSavedText:D,clearExistingIdentity:function(){v=!0;h="";s="username";p=!1;l()},useIdentity:F,renderEdit:function(a,c,b,d){document.getElementById("hint_save_edit").innerHTML=d;d=a.length;for(var g=document.getElementById("editlist");g.firstChild;)g.removeChild(g.firstChild);var e;for(e=0;e<d;e++)g.appendChild(O(a[e],c,b))},renderIdentities:function(a,c,b,d,e,f,h,m,l,n,p,r,v,s,u){""===w&&(w=b);
""===y&&(y=d);""===z&&(z=e);""===x&&(x=v);for(b=document.getElementById("idlist");b.firstChild;)b.removeChild(b.firstChild);if(0===m)B=!1,I(),D(a,c,0);else if(1===m){B=!0;var t=null,q;for(q in l)l.hasOwnProperty(q)&&(t=l[q]);D(a,c,1);b.appendChild(M(t,s||u,f,h));p?E(t.identity.username):n||(t.active?A():F(t.identity.username,t.identity.thumbnail,!1))}else{B=!0;d=l.length;for(q=0;q<d;q++)b.appendChild(M(l[q],s||u,f,h));D(a,c,m);if(p){a=window.location.search.substring(1).split("\x26");for(q=0;q<a.length;q++)if(c=
a[q].split("\x3d"),"ec"===c[0]){t=c[1];break}"301"===t||"302"===t?(document.getElementById("chooser_error").innerHTML=document.getElementById("error").innerHTML,A(!0)):E()}else n||A()}n&&(p?E(r,!0):F(r,"/img/userprofile/default_profile_45.png",!0))},noSavedIdentity:I}}();

//# sourceMappingURL=/javascript/1448273972000/sfdc/source/LoginHint198.js.map
